In [1]:
import numpy as np 

In [2]:
#import numpy
#numpy.version.version

'1.14.3'

In [13]:
#import numpy
#np.show_config()

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']


In [15]:
null = np.zeros (10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
import numpy as np
null = np.zeros(10)
print("%d bytes" % (null.size * null.itemsize))

80 bytes


In [40]:
Z = np.random.random((10,5)) #((y or vertical, x or horizontal))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
Z

0.016485385552345577 0.9947750442528261


array([[0.10294282, 0.99477504, 0.09761798, 0.10329774, 0.60679697],
       [0.35741659, 0.8296401 , 0.64434069, 0.18072257, 0.86995971],
       [0.47496993, 0.56718475, 0.24336635, 0.55142849, 0.46837985],
       [0.14007438, 0.4277458 , 0.67268069, 0.78336469, 0.93511711],
       [0.66229838, 0.42962255, 0.37929888, 0.57619373, 0.30806494],
       [0.54270335, 0.67215816, 0.6019987 , 0.59353573, 0.76632394],
       [0.39911552, 0.75332856, 0.14694416, 0.18550651, 0.40879678],
       [0.34053362, 0.32793945, 0.49408992, 0.72724567, 0.90140708],
       [0.31426575, 0.51319671, 0.74818804, 0.08972338, 0.95931495],
       [0.71717941, 0.58143669, 0.01648539, 0.95496349, 0.73151637]])

In [45]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5578137864055298


In [55]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.09303584 0.15955732 0.18324702 0.21543225 0.41554931 0.5517455
 0.70998794 0.73863225 0.80733837 0.92616078]
